[project]
name = "hexlet-code"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "Django>=4.2",
    "gunicorn",
    "psycopg2-binary",
    "python-dotenv",
    "dj-database-url",
    "django-filter",
    "django-bootstrap5",
    "rollbar>=0.16.3",
]

[tool.uv]

[tool.setuptools.packages.find]
include = ["task_manager*"]
exclude = ["tests*", "templates*", "staticfiles*", ".venv*", "venv*"]
