[project]
name = "hexlet-code"
version = "0.1.0"
dependencies = [
    "Django>=4.2",
    "gunicorn",
    "psycopg2-binary",
    "python-dotenv",
    "dj-database-url",
    "django-bootstrap5",
]

[tool.uv]

