name: tests-and-sonar

on:
  push:
  pull_request:

jobs:
  tests-and-sonar:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: task_manager.settings
      DATABASE_URL: sqlite:////tmp/ci.sqlite3
      PYTHONPATH: ${{ github.workspace }}
      ROLLBAR_ACCESS_TOKEN: ""
      ROLLBAR_ENV: ci
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install project (dev)
        run: uv sync --all-extras --dev

      - name: Ensure DJANGO_SECRET_KEY
        shell: bash
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-ci-$(python - <<'PY'import secrets; print(secrets.token_urlsafe(64))PY)}" >> "$GITHUB_ENV"

      - name: Migrate DB
        run: uv run python manage.py migrate --noinput

      - name: Run tests with coverage (pytest-cov)
        run: uv run pytest -q --cov=task_manager --cov-report=xml

      - name: Verify coverage is present
        run: ls -la coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=D4rkli_python-project-52
            -Dsonar.organization=d4rkli
            -Dsonar.python.version=3.12
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/migrations/**,staticfiles/**,**/*.po
